{
 "title": "EGI Accounting Portal Replacement & PEAR Prototype",
 "time": { "from": "2025-11-15T00:00:00.000Z", "to": "2026-02-15T23:59:59.000Z" },
 "templating": {
  "list": [
   { "name": "influxdb_measurement", "query": "${VAR_INFLUXDB_MEASUREMENT}" },
   {
    "name": "infra",
    "label": "Infrastructure",
    "query": {
     "query": "SHOW TAG VALUES FROM \"$influxdb_measurement\" WITH KEY = \"infra\" WHERE $timeFilter"
    }
   },
   {
    "name": "tier",
    "label": "Tier",
    "query": {
     "query": "SHOW TAG VALUES FROM \"$influxdb_measurement\" WITH KEY = \"tier\" WHERE $timeFilter"
    }
   },
   {
    "name": "country",
    "label": "Country",
    "query": {
     "query": "SHOW TAG VALUES FROM \"$influxdb_measurement\" WITH KEY = \"country\" WHERE $timeFilter"
    }
   },
   {
    "name": "ngi",
    "label": "NGI",
    "query": {
     "query": "SHOW TAG VALUES FROM \"$influxdb_measurement\" WITH KEY = \"ngi\" WHERE $timeFilter"
    }
   },
   {
    "name": "federation",
    "label": "Federation",
    "query": {
     "query": "SHOW TAG VALUES FROM \"$influxdb_measurement\" WITH KEY = \"federation\" WHERE $timeFilter"
    }
   },
   {
    "name": "vo",
    "label": "VO",
    "query": {
     "query": "SHOW TAG VALUES FROM \"$influxdb_measurement\" WITH KEY = \"vo\" WHERE $timeFilter AND \"tier\" =~ /^$tier$/ AND \"country\" =~ /^$country$/ AND \"ngi\" =~ /^$ngi$/ AND \"federation\" =~ /^$federation$/"
    }
   },
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "SHOW TAG VALUES FROM \"$influxdb_measurement\" WITH KEY = \"site\" WHERE $timeFilter AND \"tier\" =~ /^$tier$/ AND \"country\" =~ /^$country$/ AND \"ngi\" =~ /^$ngi$/ AND \"federation\" =~ /^$federation$/"
    }
   },
   {
    "name": "benchmark",
    "label": "Benchmark",
    "query": {
     "query": "SHOW TAG VALUES FROM \"$influxdb_measurement\" WITH KEY = \"benchmark\" WHERE $timeFilter"
    }
   },
   {
    "name": "groupby",
    "label": "Group By",
    "query": {
     "query": "SHOW TAG KEYS FROM \"$influxdb_measurement\""
    }
   }
  ]
 },
 "panels": [
  { "title": "Historical Charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Wall-Clock Time (core-hours)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_$groupby",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "$groupby" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$influxdb_measurement",
     "query": "SELECT sum(\"raw_wc_time\") FROM \"$influxdb_measurement\" WHERE (\"infra\" =~ /^$infra$/ AND \"benchmark\" =~ /^$benchmark$/ AND \"vo\" =~ /^$vo$/ AND \"tier\" =~ /^$tier$/ AND \"country\" =~ /^$country$/ AND \"federation\" =~ /^$federation$/ AND \"ngi\" =~ /^$ngi$/ AND \"site\" =~ /^$site$/) AND $timeFilter GROUP BY time(1d), \"$groupby\" fill(none)",
     "select": [
      [
       { "params": [ "raw_wc_time" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "vo", "operator": "=~", "value": "/^$vo$/" },
      { "condition": "AND", "key": "tier", "operator": "=~", "value": "/^$tier$/" },
      { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "federation", "operator": "=~", "value": "/^$federation$/" },
      { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Wall-Clock Work (HS23 core-hours)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_$groupby",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "$groupby" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$influxdb_measurement",
     "query": "SELECT sum(\"raw_wc_work\") FROM \"$influxdb_measurement\" WHERE (\"infra\" =~ /^$infra$/ AND \"benchmark\" =~ /^$benchmark$/ AND \"vo\" =~ /^$vo$/ AND \"tier\" =~ /^$tier$/ AND \"country\" =~ /^$country$/ AND \"federation\" =~ /^$federation$/ AND \"ngi\" =~ /^$ngi$/ AND \"site\" =~ /^$site$/) AND $timeFilter GROUP BY time(1d), \"$groupby\" fill(none)",
     "select": [
      [
       { "params": [ "raw_wc_work" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "vo", "operator": "=~", "value": "/^$vo$/" },
      { "condition": "AND", "key": "tier", "operator": "=~", "value": "/^$tier$/" },
      { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "federation", "operator": "=~", "value": "/^$federation$/" },
      { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Time (hours)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_$groupby",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "$groupby" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$influxdb_measurement",
     "query": "SELECT sum(\"raw_cpu_time\") FROM \"$influxdb_measurement\" WHERE (\"infra\" =~ /^$infra$/ AND \"benchmark\" =~ /^$benchmark$/ AND \"vo\" =~ /^$vo$/ AND \"tier\" =~ /^$tier$/ AND \"country\" =~ /^$country$/ AND \"federation\" =~ /^$federation$/ AND \"ngi\" =~ /^$ngi$/ AND \"site\" =~ /^$site$/) AND $timeFilter GROUP BY time(1d), \"$groupby\" fill(none)",
     "select": [
      [
       { "params": [ "raw_wc_time" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "vo", "operator": "=~", "value": "/^$vo$/" },
      { "condition": "AND", "key": "tier", "operator": "=~", "value": "/^$tier$/" },
      { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "federation", "operator": "=~", "value": "/^$federation$/" },
      { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Work (HS23 hours)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_$groupby",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "$groupby" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$influxdb_measurement",
     "query": "SELECT sum(\"raw_cpu_work\") FROM \"$influxdb_measurement\" WHERE (\"infra\" =~ /^$infra$/ AND \"benchmark\" =~ /^$benchmark$/ AND \"vo\" =~ /^$vo$/ AND \"tier\" =~ /^$tier$/ AND \"country\" =~ /^$country$/ AND \"federation\" =~ /^$federation$/ AND \"ngi\" =~ /^$ngi$/ AND \"site\" =~ /^$site$/) AND $timeFilter GROUP BY time(1d), \"$groupby\" fill(none)",
     "select": [
      [
       { "params": [ "raw_wc_work" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "vo", "operator": "=~", "value": "/^$vo$/" },
      { "condition": "AND", "key": "tier", "operator": "=~", "value": "/^$tier$/" },
      { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "federation", "operator": "=~", "value": "/^$federation$/" },
      { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Efficiency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$tag_$groupby",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "$groupby" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$influxdb_measurement",
     "query": "SELECT SUM(\"raw_cpu_work\") / SUM(\"raw_wc_work\") FROM \"$influxdb_measurement\" WHERE (\"infra\" =~ /^$infra$/ AND \"benchmark\" =~ /^$benchmark$/ AND \"vo\" =~ /^$vo$/ AND \"tier\" =~ /^$tier$/ AND \"country\" =~ /^$country$/ AND \"federation\" =~ /^$federation$/ AND \"ngi\" =~ /^$ngi$/ AND \"site\" =~ /^$site$/) AND $timeFilter GROUP BY time(1d), \"$groupby\" fill(none)",
     "select": [
      [
       { "params": [ "raw_cpu_eff" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "vo", "operator": "=~", "value": "/^$vo$/" },
      { "condition": "AND", "key": "tier", "operator": "=~", "value": "/^$tier$/" },
      { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "federation", "operator": "=~", "value": "/^$federation$/" },
      { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 25 },
   "options": {
    "content": "<h5 style=\"font-weight: normal;\">\n  Historical Charts - High Throughput\n</h5>"
   }
  },
  {
   "title": "Number of Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_$groupby",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "$groupby" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$influxdb_measurement",
     "query": "SELECT sum(\"job_count\") FROM \"$influxdb_measurement\" WHERE (\"infra\" =~ /^$infra$/ AND \"benchmark\" =~ /^$benchmark$/ AND \"vo\" =~ /^$vo$/ AND \"tier\" =~ /^$tier$/ AND \"country\" =~ /^$country$/ AND \"federation\" =~ /^$federation$/ AND \"ngi\" =~ /^$ngi$/ AND \"site\" =~ /^$site$/) AND $timeFilter GROUP BY time(1d), \"$groupby\" fill(none)",
     "select": [
      [
       { "params": [ "raw_wc_time" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "vo", "operator": "=~", "value": "/^$vo$/" },
      { "condition": "AND", "key": "tier", "operator": "=~", "value": "/^$tier$/" },
      { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "federation", "operator": "=~", "value": "/^$federation$/" },
      { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 35 },
   "options": {
    "content": "<h5 style=\"font-weight: normal;\">\n  Historical Charts - Cloud Compute\n</h5>"
   }
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "$tag_$groupby",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "$groupby" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$influxdb_measurement",
     "query": "SELECT sum(\"memory_used\") FROM \"$influxdb_measurement\" WHERE (\"infra\" =~ /^$infra$/ AND \"benchmark\" =~ /^$benchmark$/ AND \"vo\" =~ /^$vo$/ AND \"tier\" =~ /^$tier$/ AND \"country\" =~ /^$country$/ AND \"federation\" =~ /^$federation$/ AND \"ngi\" =~ /^$ngi$/ AND \"site\" =~ /^$site$/) AND $timeFilter GROUP BY time(1d), \"$groupby\" fill(none)",
     "select": [
      [
       { "params": [ "raw_wc_time" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "vo", "operator": "=~", "value": "/^$vo$/" },
      { "condition": "AND", "key": "tier", "operator": "=~", "value": "/^$tier$/" },
      { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "federation", "operator": "=~", "value": "/^$federation$/" },
      { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "alias": "$tag_$groupby",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "$groupby" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$influxdb_measurement",
     "query": "SELECT sum(\"disk_used\") FROM \"$influxdb_measurement\" WHERE (\"infra\" =~ /^$infra$/ AND \"benchmark\" =~ /^$benchmark$/ AND \"vo\" =~ /^$vo$/ AND \"tier\" =~ /^$tier$/ AND \"country\" =~ /^$country$/ AND \"federation\" =~ /^$federation$/ AND \"ngi\" =~ /^$ngi$/ AND \"site\" =~ /^$site$/) AND $timeFilter GROUP BY time(1d), \"$groupby\" fill(none)",
     "select": [
      [
       { "params": [ "raw_wc_time" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "vo", "operator": "=~", "value": "/^$vo$/" },
      { "condition": "AND", "key": "tier", "operator": "=~", "value": "/^$tier$/" },
      { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "federation", "operator": "=~", "value": "/^$federation$/" },
      { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of VMs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_$groupby",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "$groupby" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$influxdb_measurement",
     "query": "SELECT sum(\"vm_count\") FROM \"$influxdb_measurement\" WHERE (\"infra\" =~ /^$infra$/ AND \"benchmark\" =~ /^$benchmark$/ AND \"vo\" =~ /^$vo$/ AND \"tier\" =~ /^$tier$/ AND \"country\" =~ /^$country$/ AND \"federation\" =~ /^$federation$/ AND \"ngi\" =~ /^$ngi$/ AND \"site\" =~ /^$site$/) AND $timeFilter GROUP BY time(1d), \"$groupby\" fill(none)",
     "select": [
      [
       { "params": [ "raw_wc_time" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "vo", "operator": "=~", "value": "/^$vo$/" },
      { "condition": "AND", "key": "tier", "operator": "=~", "value": "/^$tier$/" },
      { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "federation", "operator": "=~", "value": "/^$federation$/" },
      { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of Cores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_$groupby",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "$groupby" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$influxdb_measurement",
     "query": "SELECT sum(\"cpu_core_count\") FROM \"$influxdb_measurement\" WHERE (\"infra\" =~ /^$infra$/ AND \"benchmark\" =~ /^$benchmark$/ AND \"vo\" =~ /^$vo$/ AND \"tier\" =~ /^$tier$/ AND \"country\" =~ /^$country$/ AND \"federation\" =~ /^$federation$/ AND \"ngi\" =~ /^$ngi$/ AND \"site\" =~ /^$site$/) AND $timeFilter GROUP BY time(1d), \"$groupby\" fill(none)",
     "select": [
      [
       { "params": [ "raw_wc_time" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "vo", "operator": "=~", "value": "/^$vo$/" },
      { "condition": "AND", "key": "tier", "operator": "=~", "value": "/^$tier$/" },
      { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "federation", "operator": "=~", "value": "/^$federation$/" },
      { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Inbound Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_$groupby",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "$groupby" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$influxdb_measurement",
     "query": "SELECT sum(\"network_in\") FROM \"$influxdb_measurement\" WHERE (\"infra\" =~ /^$infra$/ AND \"benchmark\" =~ /^$benchmark$/ AND \"vo\" =~ /^$vo$/ AND \"tier\" =~ /^$tier$/ AND \"country\" =~ /^$country$/ AND \"federation\" =~ /^$federation$/ AND \"ngi\" =~ /^$ngi$/ AND \"site\" =~ /^$site$/) AND $timeFilter GROUP BY time(1d), \"$groupby\" fill(none)",
     "select": [
      [
       { "params": [ "raw_wc_time" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "vo", "operator": "=~", "value": "/^$vo$/" },
      { "condition": "AND", "key": "tier", "operator": "=~", "value": "/^$tier$/" },
      { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "federation", "operator": "=~", "value": "/^$federation$/" },
      { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  {
   "title": "Outbound Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_$groupby",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "$groupby" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$influxdb_measurement",
     "query": "SELECT sum(\"network_out\") FROM \"$influxdb_measurement\" WHERE (\"infra\" =~ /^$infra$/ AND \"benchmark\" =~ /^$benchmark$/ AND \"vo\" =~ /^$vo$/ AND \"tier\" =~ /^$tier$/ AND \"country\" =~ /^$country$/ AND \"federation\" =~ /^$federation$/ AND \"ngi\" =~ /^$ngi$/ AND \"site\" =~ /^$site$/) AND $timeFilter GROUP BY time(1d), \"$groupby\" fill(none)",
     "select": [
      [
       { "params": [ "raw_wc_time" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "vo", "operator": "=~", "value": "/^$vo$/" },
      { "condition": "AND", "key": "tier", "operator": "=~", "value": "/^$tier$/" },
      { "condition": "AND", "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "federation", "operator": "=~", "value": "/^$federation$/" },
      { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" }
     ]
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Summary: CPU consumption metrics",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "$groupby" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$influxdb_measurement",
     "query": "    SELECT\n        SUM(\"raw_wc_time\") AS \"Wall-Clock Time (core-hours)\",\n        SUM(\"raw_wc_work\") AS \"Wall-Clock Work (HS23 core-hours)\",\n        SUM(\"raw_cpu_time\") AS \"CPU Time (hours)\",\n        SUM(\"raw_cpu_work\") AS \"CPU Work (HS23 hours)\",\n        SUM(\"raw_cpu_work\") / SUM(\"raw_wc_work\") AS \"CPU Efficiency\"\n    FROM \"$influxdb_measurement\"\n    WHERE\n        $timeFilter\n        AND \"infra\" =~ /^$infra$/\n        AND \"benchmark\" =~ /^$benchmark$/\n        AND \"vo\" =~ /^$vo$/\n        AND \"tier\" =~ /^$tier$/\n        AND \"country\" =~ /^$country$/\n        AND \"federation\" =~ /^$federation$/\n        AND \"ngi\" =~ /^$ngi$/\n        AND \"site\" =~ /^$site$/\nGROUP BY\n    \"$groupby\"\n    fill(none)",
     "select": [
      [
       { "params": [ "wc_time" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "WCT" ], "type": "alias" }
      ],
      [
       { "params": [ "wc_work" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "WCW" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "federation", "operator": "=~", "value": "/^$federation$/" },
      { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
      { "condition": "AND", "key": "tier", "operator": "=~", "value": "/^$tier$/" },
      { "condition": "AND", "key": "vo", "operator": "=~", "value": "/^$vo$/" }
     ]
    }
   ]
  },
  {
   "title": "Summary: HTC Number of Jobs",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "$groupby" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$influxdb_measurement",
     "query": "    SELECT\n        SUM(\"job_count\") AS \"Number of Jobs\"\n    FROM \"$influxdb_measurement\"\n    WHERE\n        $timeFilter\n        AND \"infra\" =~ /^$infra$/\n        AND \"benchmark\" =~ /^$benchmark$/\n        AND \"vo\" =~ /^$vo$/\n        AND \"tier\" =~ /^$tier$/\n        AND \"country\" =~ /^$country$/\n        AND \"federation\" =~ /^$federation$/\n        AND \"ngi\" =~ /^$ngi$/\n        AND \"site\" =~ /^$site$/\nGROUP BY\n    \"$groupby\"\n    fill(none)",
     "select": [
      [
       { "params": [ "wc_time" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "WCT" ], "type": "alias" }
      ],
      [
       { "params": [ "wc_work" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "WCW" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "federation", "operator": "=~", "value": "/^$federation$/" },
      { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
      { "condition": "AND", "key": "tier", "operator": "=~", "value": "/^$tier$/" },
      { "condition": "AND", "key": "vo", "operator": "=~", "value": "/^$vo$/" }
     ]
    }
   ]
  },
  {
   "title": "Summary: Cloud Compute specific metrics",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "$groupby" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$influxdb_measurement",
     "query": "    SELECT\n     SUM(\"memory_used\") AS \"Memory Used\",\n     SUM(\"disk_used\") AS \"Disk Used\",\n     SUM(\"vm_count\") AS \"Number of VMs\",\n     SUM(\"cpu_core_count\") AS \"Number of Cores\",\n     SUM(\"network_in\") AS \"Inbound Network Traffic\",\n     SUM(\"network_out\") AS \"Outbound Network Traffic\"\n    FROM \"$influxdb_measurement\"\n    WHERE\n        $timeFilter\n        AND \"infra\" =~ /^$infra$/\n        AND \"benchmark\" =~ /^$benchmark$/\n        AND \"vo\" =~ /^$vo$/\n        AND \"tier\" =~ /^$tier$/\n        AND \"country\" =~ /^$country$/\n        AND \"federation\" =~ /^$federation$/\n        AND \"ngi\" =~ /^$ngi$/\n        AND \"site\" =~ /^$site$/\nGROUP BY\n    \"$groupby\"\n    fill(none)",
     "select": [
      [
       { "params": [ "wc_time" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "WCT" ], "type": "alias" }
      ],
      [
       { "params": [ "wc_work" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "WCW" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "federation", "operator": "=~", "value": "/^$federation$/" },
      { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
      { "condition": "AND", "key": "tier", "operator": "=~", "value": "/^$tier$/" },
      { "condition": "AND", "key": "vo", "operator": "=~", "value": "/^$vo$/" }
     ]
    }
   ]
  },
  { "title": "Part-to-Whole Charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Wall-Clock Time (core-hours)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_$groupby",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "$groupby" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$influxdb_measurement",
     "query": "SELECT sum(\"raw_wc_time\") FROM \"$influxdb_measurement\" WHERE (\"infra\" =~ /^$infra$/ AND \"benchmark\" =~ /^$benchmark$/ AND \"vo\" =~ /^$vo$/ AND \"tier\" =~ /^$tier$/ AND \"country\" =~ /^$country$/ AND \"federation\" =~ /^$federation$/ AND \"ngi\" =~ /^$ngi$/ AND \"site\" =~ /^$site$/) AND $timeFilter GROUP BY \"$groupby\" fill(none)",
     "select": [
      [
       { "params": [ "raw_wc_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "federation", "operator": "=~", "value": "/^$federation$/" },
      { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
      { "condition": "AND", "key": "tier", "operator": "=~", "value": "/^$tier$/" },
      { "condition": "AND", "key": "vo", "operator": "=~", "value": "/^$vo$/" }
     ]
    }
   ]
  },
  {
   "title": "Wall-Clock Work (HS23 core-hours)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_$groupby",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "$groupby" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$influxdb_measurement",
     "query": "SELECT sum(\"raw_wc_work\") FROM \"$influxdb_measurement\" WHERE (\"infra\" =~ /^$infra$/ AND \"benchmark\" =~ /^$benchmark$/ AND \"vo\" =~ /^$vo$/ AND \"tier\" =~ /^$tier$/ AND \"country\" =~ /^$country$/ AND \"federation\" =~ /^$federation$/ AND \"ngi\" =~ /^$ngi$/ AND \"site\" =~ /^$site$/) AND $timeFilter GROUP BY \"$groupby\" fill(none)",
     "select": [
      [
       { "params": [ "raw_wc_work" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "federation", "operator": "=~", "value": "/^$federation$/" },
      { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
      { "condition": "AND", "key": "tier", "operator": "=~", "value": "/^$tier$/" },
      { "condition": "AND", "key": "vo", "operator": "=~", "value": "/^$vo$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Time (hours)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_$groupby",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "$groupby" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$influxdb_measurement",
     "query": "SELECT sum(\"raw_cpu_time\") FROM \"$influxdb_measurement\" WHERE (\"infra\" =~ /^$infra$/ AND \"benchmark\" =~ /^$benchmark$/ AND \"vo\" =~ /^$vo$/ AND \"tier\" =~ /^$tier$/ AND \"country\" =~ /^$country$/ AND \"federation\" =~ /^$federation$/ AND \"ngi\" =~ /^$ngi$/ AND \"site\" =~ /^$site$/) AND $timeFilter GROUP BY \"$groupby\" fill(none)",
     "select": [
      [
       { "params": [ "raw_wc_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "federation", "operator": "=~", "value": "/^$federation$/" },
      { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
      { "condition": "AND", "key": "tier", "operator": "=~", "value": "/^$tier$/" },
      { "condition": "AND", "key": "vo", "operator": "=~", "value": "/^$vo$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Work (HS23 hours)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_$groupby",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "$groupby" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$influxdb_measurement",
     "query": "SELECT sum(\"raw_cpu_work\") FROM \"$influxdb_measurement\" WHERE (\"infra\" =~ /^$infra$/ AND \"benchmark\" =~ /^$benchmark$/ AND \"vo\" =~ /^$vo$/ AND \"tier\" =~ /^$tier$/ AND \"country\" =~ /^$country$/ AND \"federation\" =~ /^$federation$/ AND \"ngi\" =~ /^$ngi$/ AND \"site\" =~ /^$site$/) AND $timeFilter GROUP BY \"$groupby\" fill(none)",
     "select": [
      [
       { "params": [ "raw_wc_work" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "federation", "operator": "=~", "value": "/^$federation$/" },
      { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
      { "condition": "AND", "key": "tier", "operator": "=~", "value": "/^$tier$/" },
      { "condition": "AND", "key": "vo", "operator": "=~", "value": "/^$vo$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 100 },
   "options": {
    "content": "<h5 style=\"font-weight: normal;\">\n  Part-to-Whole Charts - High Throughput\n</h5>"
   }
  },
  {
   "title": "Number of Jobs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_$groupby",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "$groupby" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$influxdb_measurement",
     "query": "SELECT sum(\"job_count\") FROM \"$influxdb_measurement\" WHERE (\"infra\" =~ /^$infra$/ AND \"benchmark\" =~ /^$benchmark$/ AND \"vo\" =~ /^$vo$/ AND \"tier\" =~ /^$tier$/ AND \"country\" =~ /^$country$/ AND \"federation\" =~ /^$federation$/ AND \"ngi\" =~ /^$ngi$/ AND \"site\" =~ /^$site$/) AND $timeFilter GROUP BY \"$groupby\" fill(none)",
     "select": [
      [
       { "params": [ "raw_wc_work" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "federation", "operator": "=~", "value": "/^$federation$/" },
      { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
      { "condition": "AND", "key": "tier", "operator": "=~", "value": "/^$tier$/" },
      { "condition": "AND", "key": "vo", "operator": "=~", "value": "/^$vo$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 110 },
   "options": {
    "content": "<h5 style=\"font-weight: normal;\">\n  Part-to-Whole Charts - Cloud Compute\n</h5>"
   }
  },
  {
   "title": "Memory Used",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "$tag_$groupby",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "$groupby" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$influxdb_measurement",
     "query": "SELECT sum(\"memory_used\") FROM \"$influxdb_measurement\" WHERE (\"infra\" =~ /^$infra$/ AND \"benchmark\" =~ /^$benchmark$/ AND \"vo\" =~ /^$vo$/ AND \"tier\" =~ /^$tier$/ AND \"country\" =~ /^$country$/ AND \"federation\" =~ /^$federation$/ AND \"ngi\" =~ /^$ngi$/ AND \"site\" =~ /^$site$/) AND $timeFilter GROUP BY \"$groupby\" fill(none)",
     "select": [
      [
       { "params": [ "raw_wc_work" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "federation", "operator": "=~", "value": "/^$federation$/" },
      { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
      { "condition": "AND", "key": "tier", "operator": "=~", "value": "/^$tier$/" },
      { "condition": "AND", "key": "vo", "operator": "=~", "value": "/^$vo$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "alias": "$tag_$groupby",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "$groupby" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$influxdb_measurement",
     "query": "SELECT sum(\"disk_used\") FROM \"$influxdb_measurement\" WHERE (\"infra\" =~ /^$infra$/ AND \"benchmark\" =~ /^$benchmark$/ AND \"vo\" =~ /^$vo$/ AND \"tier\" =~ /^$tier$/ AND \"country\" =~ /^$country$/ AND \"federation\" =~ /^$federation$/ AND \"ngi\" =~ /^$ngi$/ AND \"site\" =~ /^$site$/) AND $timeFilter GROUP BY \"$groupby\" fill(none)",
     "select": [
      [
       { "params": [ "raw_wc_work" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "federation", "operator": "=~", "value": "/^$federation$/" },
      { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
      { "condition": "AND", "key": "tier", "operator": "=~", "value": "/^$tier$/" },
      { "condition": "AND", "key": "vo", "operator": "=~", "value": "/^$vo$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of VMs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_$groupby",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "$groupby" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$influxdb_measurement",
     "query": "SELECT sum(\"vm_count\") FROM \"$influxdb_measurement\" WHERE (\"infra\" =~ /^$infra$/ AND \"benchmark\" =~ /^$benchmark$/ AND \"vo\" =~ /^$vo$/ AND \"tier\" =~ /^$tier$/ AND \"country\" =~ /^$country$/ AND \"federation\" =~ /^$federation$/ AND \"ngi\" =~ /^$ngi$/ AND \"site\" =~ /^$site$/) AND $timeFilter GROUP BY \"$groupby\" fill(none)",
     "select": [
      [
       { "params": [ "raw_wc_work" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "federation", "operator": "=~", "value": "/^$federation$/" },
      { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
      { "condition": "AND", "key": "tier", "operator": "=~", "value": "/^$tier$/" },
      { "condition": "AND", "key": "vo", "operator": "=~", "value": "/^$vo$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of Cores",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_$groupby",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "$groupby" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$influxdb_measurement",
     "query": "SELECT sum(\"cpu_core_count\") FROM \"$influxdb_measurement\" WHERE (\"infra\" =~ /^$infra$/ AND \"benchmark\" =~ /^$benchmark$/ AND \"vo\" =~ /^$vo$/ AND \"tier\" =~ /^$tier$/ AND \"country\" =~ /^$country$/ AND \"federation\" =~ /^$federation$/ AND \"ngi\" =~ /^$ngi$/ AND \"site\" =~ /^$site$/) AND $timeFilter GROUP BY \"$groupby\" fill(none)",
     "select": [
      [
       { "params": [ "raw_wc_work" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "federation", "operator": "=~", "value": "/^$federation$/" },
      { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
      { "condition": "AND", "key": "tier", "operator": "=~", "value": "/^$tier$/" },
      { "condition": "AND", "key": "vo", "operator": "=~", "value": "/^$vo$/" }
     ]
    }
   ]
  },
  {
   "title": "Inbound Network Traffic",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_$groupby",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "$groupby" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$influxdb_measurement",
     "query": "SELECT sum(\"network_in\") FROM \"$influxdb_measurement\" WHERE (\"infra\" =~ /^$infra$/ AND \"benchmark\" =~ /^$benchmark$/ AND \"vo\" =~ /^$vo$/ AND \"tier\" =~ /^$tier$/ AND \"country\" =~ /^$country$/ AND \"federation\" =~ /^$federation$/ AND \"ngi\" =~ /^$ngi$/ AND \"site\" =~ /^$site$/) AND $timeFilter GROUP BY \"$groupby\" fill(none)",
     "select": [
      [
       { "params": [ "raw_wc_work" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "federation", "operator": "=~", "value": "/^$federation$/" },
      { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
      { "condition": "AND", "key": "tier", "operator": "=~", "value": "/^$tier$/" },
      { "condition": "AND", "key": "vo", "operator": "=~", "value": "/^$vo$/" }
     ]
    }
   ]
  },
  {
   "title": "Outbound Network Traffic",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_$groupby",
     "groupBy": [
      { "params": [ "30d" ], "type": "time" },
      { "params": [ "$groupby" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "$influxdb_measurement",
     "query": "SELECT sum(\"network_out\") FROM \"$influxdb_measurement\" WHERE (\"infra\" =~ /^$infra$/ AND \"benchmark\" =~ /^$benchmark$/ AND \"vo\" =~ /^$vo$/ AND \"tier\" =~ /^$tier$/ AND \"country\" =~ /^$country$/ AND \"federation\" =~ /^$federation$/ AND \"ngi\" =~ /^$ngi$/ AND \"site\" =~ /^$site$/) AND $timeFilter GROUP BY \"$groupby\" fill(none)",
     "select": [
      [
       { "params": [ "raw_wc_work" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "federation", "operator": "=~", "value": "/^$federation$/" },
      { "condition": "AND", "key": "site", "operator": "=~", "value": "/^$site$/" },
      { "condition": "AND", "key": "tier", "operator": "=~", "value": "/^$tier$/" },
      { "condition": "AND", "key": "vo", "operator": "=~", "value": "/^$vo$/" }
     ]
    }
   ]
  }
 ]
}