kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: apel-consumer-output
spec:
  storageClassName: meyrin-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
